version: "3.9"

services:
  assignment_service:
    image: assignment_service:1.0.0
    container_name: assignment_service
    ports:
      - 3000:3000
    restart: always
    volumes:
      - "./templates:/mnt/templates"
    env_file:
      - .env
